repos:
  - repo: local
    hooks:
    - id: flake8-moshi
      name: flake8 on moshi package
      language: system
      entry: bash -c 'cd moshi && flake8'
      pass_filenames: false
    hooks:
    - id: pyright-moshi
      name: pyrgith on moshi package
      language: system
      entry: bash -c 'cd moshi && pyright'
      pass_filenames: false

